### ISSUE TITLE
logs.libuv.org appears down

### ISSUE THREAD

**Issue by cspotcode** [libuv/libuv.github.io#3]
This is the closest place I could find to ask this question, though I doubt logs.libuv.org is related to the code in this repository.

It appears to be down; do you know where it's hosted or how to contact the owner to ask about getting it fixed?

**Comment by bnoordhuis** [comment]
@piscisaureus hosts it and I believe I should be able to log in if I remembered how. We should probably migrate or sunset it because neither of us has a lot of free time these days.

**Comment by piscisaureus** [comment]
logs.libuv.org has been sunset. 
An archive of the logs can be found at https://github.com/piscisaureus/slurp-logs

**Comment by cspotcode** [comment]
Ok, good to know, thank you.  Looking at the logs, it was sunset after 2020-01-31?

Linking to https://github.com/libuv/libuv/issues/3208

I came here after trying to use node's #node-dev channel.  Unfortunately freenode has blocked IRCCloud, and I wasn't able to keep a client open all day, so I'm not sure if my questions went totally unanswered or if they were answered in my absence.  I did not see anyone saying anything while I was logged in.  Do you know if #node-dev is still a viable place for discussing node core development?  Or should I create some issues / PRs to update node's documentation and remove mentions of the IRC channel, perhaps updating to point to a Slack or a Discord server?

Again, I realize this may not be the correct place to ask, and I can move my questions elsewhere if needed.

**Comment by richardlau** [comment]
@cspotcode For the Node.js channels such as #node-dev https://github.com/nodejs/TSC/issues/1031 is where the discussion about the IRC channels is going on.

**Comment by cspotcode** [comment]
Ah, much appreciated.  I will close this as answered; thanks everyone!
